# 是否开启日志
log: true
# 是否开启本地仓库（file://该配置所在目录/repository/）
# 开启后会导致快照版本的工件无法自动获取更新
local: false

# maven 仓库地址 工件检索次序由上到下
##############################
#         自定义仓库           #
##############################
repositories:
  aliyun:
    url: https://maven.aliyun.com/repository/public/
  maven-central:
    url: https://repo1.maven.org/maven2/
  sonatype-snapshots:
    url: https://central.sonatype.com/repository/maven-snapshots/
